### PR TITLE
Fix active nav menu markup

### LINKED ISSUE #411: Bootstrap 5 with fill layout: page refresh introduces scrollbar
Hello,

With the MWE below and with the second tab active, a page refresh causes a vertical scrollbar to appear that can be used to scroll back to the first tab. Furthermore, the tab selection on the navbar revers to tab 1 while tab 2 is still active. Downgrading bootstrap isn't an option since I am using cards from `bslib`.

````r
---
title: "Themed dashboard"
output: 
    flexdashboard::flex_dashboard:
        theme:
            version: 5
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Tab 1
==========

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Chart A

### Chart B

Tab 2
==========

Column {data-width=350}
-----------------------------------------------------------------------

### Chart C

### Chart D
````

A partial solution is with
```html
html, body {
    overflow: hidden;
}
```

But this will of course not fix the navbar tab selection.

Thanks,
Rick

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #411

This is a minimal fix for the behavior described in #411. The root issue is that BS5 requires a `.tab-pane.active` to have a corresponding `.active` toggle item. I'm being vague because the active class can appear as either `li.nav-item.active` or `.nav-link.active`. When the active class is imbalanced in the markup in BS5, the `.active` class isn't removed from the imbalanced `.tab-pane` until after it's activated.

https://user-images.githubusercontent.com/5420529/220937196-748eb254-4f90-44f0-93b3-46c2736bf4d8.mp4

The clip above uses the markup created by flexdashboard during initialization just [before the Bootstrap tab plugin is invoked](https://github.com/rstudio/flexdashboard/blob/bf8cdc55e15e3a7cfc53ed2d186a9303d271dc48/inst/www/flex_dashboard/flexdashboard.js#L135-L136). You can observe the tab behavior in Bootstrap versions 3-5 using this Rmd:

<details><summary><code>bootstrap-tabs-init.Rmd</code></summary>

````markdown
---
title: BS Nav Test
output:
  html_document:
    theme:
      version: 5
    self_contained: false
---

> Bootstrap version <span id="bs-version">x.y.z</span>

<span id="state">⏱️ before initializing tabs</span>

## No active classes anywhere

```{=html}
<div id="no-active">
  <div class="navbar bg-light navbar-default">
    <ul class="nav navbar-nav navbar-left">
      <li class="nav-item">
        <a class="nav-link" href="#no-active-one" data-toggle="tab">One</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#no-active-two" data-toggle="tab">Two</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#no-active-three" data-toggle="tab">Three</a>
      </li>
    </ul>
  </div>

  <div class="tab-content" style="height: 100%;">
    <div class="dashboard-page-wrapper tab-pane" id="no-active-one" style="height: 100%;">one content</div>
    <div class="dashboard-page-wrapper tab-pane" id="no-active-two" style="height: 100%;">two content</div>
    <div class="dashboard-page-wrapper tab-pane" id="no-active-three" style="height: 100%;">three content</div>
  </div>
</div>
```

## Nav doesn't have active class

```{=html}
<div id="nav-no-class">
  <div class="navbar bg-light navbar-default">
    <ul class="nav navbar-nav navbar-left">
      <li class="nav-item">
        <a class="nav-link" href="#nav-no-class-one" data-toggle="tab">One</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#nav-no-class-two" data-toggle="tab">Two</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#nav-no-class-three" data-toggle="tab">Three</a>
      </li>
    </ul>
  </div>

  <div class="tab-content" style="height: 100%;">
    <div class="dashboard-page-wrapper tab-pane active" id="nav-no-class-one" style="height: 100%;">one content</div>
    <div class="dashboard-page-wrapper tab-pane" id="nav-no-class-two" style="height: 100%;">two content</div>
    <div class="dashboard-page-wrapper tab-pane" id="nav-no-class-three" style="height: 100%;">three content</div>
  </div>
</div>
```

## Nav has active class on li

```{=html}
<div id="nav-class-li">
  <div class="navbar bg-light navbar-default">
    <ul class="nav navbar-nav navbar-left">
      <li class="nav-item active">
        <a class="nav-link" href="#nav-class-li-one" data-toggle="tab">One</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#nav-class-li-two" data-toggle="tab">Two</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#nav-class-li-three" data-toggle="tab">Three</a>
      </li>
    </ul>
  </div>

  <div class="tab-content" style="height: 100%;">
    <div class="dashboard-page-wrapper tab-pane active" id="nav-class-li-one" style="height: 100%;">one content</div>
    <div class="dashboard-page-wrapper tab-pane" id="nav-class-li-two" style="height: 100%;">two content</div>
    <div class="dashboard-page-wrapper tab-pane" id="nav-class-li-three" style="height: 100%;">three content</div>
  </div>
</div>
```

## Nav has active class on li > a

```{=html}
<div id="nav-class-li-a">
  <div class="navbar bg-light navbar-default">
    <ul class="nav navbar-nav navbar-left">
      <li class="nav-item">
        <a class="nav-link active" href="#nav-class-li-a-one" data-toggle="tab">One</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#nav-class-li-a-two" data-toggle="tab">Two</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#nav-class-li-a-three" data-toggle="tab">Three</a>
      </li>
    </ul>
  </div>

  <div class="tab-content" style="height: 100%;">
    <div class="dashboard-page-wrapper tab-pane active" id="nav-class-li-a-one" style="height: 100%;">one content</div>
    <div class="dashboard-page-wrapper tab-pane" id="nav-class-li-a-two" style="height: 100%;">two content</div>
    <div class="dashboard-page-wrapper tab-pane" id="nav-class-li-a-three" style="height: 100%;">three content</div>
  </div>
</div>
```

```{=html}
<button id="activate" class="btn btn-primary" style="position: absolute; bottom: 1em; right: 1em;">activate</button>
```

```{js echo=FALSE}
$(function() {
  const bs_v = $.fn.tab.Constructor.VERSION;
  console.log(`Bootstrap version: ${bs_v}`);
  document.getElementById('bs-version').innerText = bs_v;
})

$('#activate').on('click', function() {
  ['no-active', 'nav-no-class', 'nav-class-li', 'nav-class-li-a']
    .forEach(id => {
      console.log(
        `activating #${id}, active elements:`,
        document.querySelectorAll(`#${id} .active`)
      )
      $(`[href="#${id}-two"]`).tab('show')
    })

  $('#state').text('✅ tabs ready')
})
```

````

</details>

Testing across all the three major versions of Bootstrap reveals that adding the `.active` class to the nav list item maintains consistent appearance and behavior across all versions, even if the tab plugin were to fail for some reason.

| BS | Before | After |
|:--:|:--:|:--:|
| 3 | bs3-before | bs3-after |
| 4 | bs4-before | bs4-after |
| 5 | bs5-before | bs5-after |

### CODE REVIEW

File: inst/www/flex_dashboard/flexdashboard.js [hunk 1]
```diff
@@ -299,6 +297,12 @@ var FlexDashboard = (function () {
       container.append(li);
     }
 
+    // mark active tab and corresponding nav menu item
+    if (active) {
+      wrapper.addClass('active');
+      li.addClass('active');
+    }
```
Comment (cpsievert) [inline inst/www/flex_dashboard/flexdashboard.js:304]: Apologies for just realizing this, but this feels slightly cleaner/better?

```suggestion
    if (active)
      $(a).tab("show");
```

**Comment by gadenbuie** [comment]
Now that we're calling `.tab('show')` in the navbar construction, the only code path that I can find where the call to `FlexDashboardUtils.manageActiveNavbarMenu()` is in the `.setLocation()` method of the utils.

https://github.com/rstudio/flexdashboard/blob/01b0bba637276bb9bbbf666874b00089f12daa5e/inst/www/flex_dashboard/flexdashboard.js#L1318-L1328

In every other case where `.manageActiveNavbarMenu()` is being called, we first call `.tab('show')` before the navbar is updated. My read on `.setLocation()` is that it's a way to change the page state that's driven by the content markup. In most cases, when `.tab('show')` is invoked first, the markup is already in the right place and `.setLocation()` is redundant. In the case where the active page is indicated via `.dashboard-page-wrapper.active` in a way that isn't reflected in the page URL, calling `.setLocation()` directly can update the page URL and change the active tab.

I'm... not sure why you'd want to do that, though. And looking through the change history it seems like maybe this is an artifact of how the navbar was managed initially? 

@cpsievert Anyway, I'm comfortable with this minimal fix for now and we can revisit the above notes sooner or later.

**Comment by cpsievert** [comment]
@gadenbuie thanks for doing more research and the helpful write-up. At this point, I think I'd be on board for removing it. If we do remove it though, lets maybe do as a part of this PR so that the history/discussion isn't spread across multiple commits/threads?

**Comment by gadenbuie** [comment]
> At this point, I think I'd be on board for removing it.

@cpsievert sounds good to me! I've removed the method and added notes in a couple of places where I learned things about the implementation that would be nice to remember.

I also discovered #420 while testing this, but I think that's likely better handled in a separate PR or in an upstream package.

File: inst/www/flex_dashboard/flexdashboard.js [hunk 2]
```diff
@@ -1236,16 +1239,18 @@ var FlexDashboard = (function () {
...
-      FlexDashboardUtils.manageActiveNavbarMenu();
     });
 
     // add a hash to the URL when the user clicks on a tab/page
     $('.navbar-nav a[data-toggle="tab"]').on('click', function(e) {
       var baseUrl = FlexDashboardUtils.urlWithoutHash(window.location.href);
       var hash = FlexDashboardUtils.urlHash($(this).attr('href'));
       var href = baseUrl + hash;
+      // the BS tab plugin handles changing the page and managing the navbar
+      // but flexdashboard needs to update the location and history
```
Comment (cpsievert) [inline inst/www/flex_dashboard/flexdashboard.js:1253]: I find this to be a bit redundant given the comment above (but I don't feel strongly about it, so feel free to keep it)

```suggestion
```

**Review by cpsievert — APPROVED** [review]
Thanks, feel free to merge after updating the news!

Also, it's starting to feel like we should consider putting tests (either here or in `{shinycoreci}`) for these changes as well as for https://github.com/rstudio/flexdashboard/pull/421, but we can discuss that after merging.
