### PR TITLE
Make sure DT::datatable() fills it's container sensible

### LINKED ISSUE #315: DT::datatable not working as expected
Hi, 

I recently updated R and all the packages. Since, I am seeing an unexpected behavior when viewing `DT::datatable` within a `flexdashboard`. If you run the code below, you will see that the footer of the table is not visible and you have to zoom out at least 50% to see the page numbers and total number of rows which wasn't the case before (screenshots of before and after attached: cannot reproduce before tables with mtcars so showing a table that I had generated using the same code).

Before updates, the table showed pagination, total number of rows by default. Even though it shows 6 rows but I was able to scroll vertically to see all 10 rows:
Screen Shot 2021-02-27 at 6 32 00 PM

Now, you cannot scroll vertically or horizontally and cannot see total number of rows as well as pagination:
Screen Shot 2021-02-27 at 6 38 33 PM
 
You have to zoom out to see the bottom part of a table:
Screen Shot 2021-02-27 at 6 38 46 PM

Here is a reproducible `test.Rmd` file:

    ---
    output: 
      flexdashboard::flex_dashboard:
        orientation: rows
    editor_options: 
      chunk_output_type: console
    ---
    
    ---
    title: Test
    ---
      
    ```{r include=FALSE, echo=FALSE}
    knitr::opts_chunk$set(comment = NA)
    ```
    
    
    ```{r load_libraries}
    library(DT)
    ```
    
    Tab1 (P1) {data-navmenu="Tab"}
    ===
    Row {data-height=200}
    ---   
    
    ### Some Information
    
    ```{r empty}
    ```
    
    Row {data-height=500}
    ---
      
    ### Table1
      
    ```{r table1}
    DT::datatable(mtcars)
    ```
    
    Row {data-height=300}
    ---
      
    ### Table2
      
    ```{r table2}
    DT::datatable(mtcars)
    ```

I convert the Rmd to html using:

```
rmarkdown::render(input = 'test.Rmd', output_file = "test.html")
```

My sessionInfo:

```
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] kableExtra_1.3.4 DT_0.17         

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6          later_1.1.0.1       bslib_0.2.4         compiler_4.0.4      jquerylib_0.1.3     highr_0.8          
 [7] tools_4.0.4         digest_0.6.27       jsonlite_1.7.2      evaluate_0.14       lifecycle_1.0.0     viridisLite_0.3.0  
[13] rlang_0.4.10        shiny_1.6.0         rstudioapi_0.13     crosstalk_1.1.1     yaml_2.2.1          xfun_0.21          
[19] fastmap_1.1.0       httr_1.4.2          stringr_1.4.0       knitr_1.31          xml2_1.3.2          htmlwidgets_1.5.3  
[25] sass_0.3.1          systemfonts_1.0.1   webshot_0.5.2       flexdashboard_0.5.2 svglite_2.0.0       glue_1.4.2         
[31] R6_2.5.0            rmarkdown_2.7       magrittr_2.0.1      ellipsis_0.3.1      promises_1.2.0.1    scales_1.1.1       
[37] htmltools_0.5.1.1   rvest_0.3.6         xtable_1.8-4        mime_0.10           colorspace_2.0-0    httpuv_1.5.5       
[43] tinytex_0.29        stringi_1.5.3       munsell_0.5.0      
```

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #315, #321, and #286

(And a somewhat related fix in `{DT}` -- https://github.com/rstudio/DT/pull/904)

### CODE REVIEW

File: R/flex_dashboard.R [hunk 1]
```diff
@@ -181,17 +178,7 @@ flex_dashboard <- function(fig_width = 6.0,
...
-    exit_actions <- c(exit_actions, function() {
-      options(DT.fillContainer = NULL)
-    })
-  }
-
-  # request that DT auto-hide navigation (unless the option is already set)
-  if (is.na(getOption('DT.autoHideNavigation', NA))) {
-    exit_actions <- c(exit_actions, function() {
-      options(DT.autoHideNavigation = NULL)
-    })
```
Comment (cpsievert) [inline R/flex_dashboard.R:194]: Appears this is no longer a datatables option -- https://datatables.net/reference/option/

Also appears JJ forgot to set this option anyway in this commit to restore options on exit https://github.com/rstudio/flexdashboard/commit/854a2ceb867522fa892d66417a43733e476c92ec

**Review by schloerke — APPROVED** [review]
